package eular;
/*
 * Problem 2 :

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

*/
import java.util.*;

public class q002 {
	 static void series()
	{
     	int f1=0;
		int f2=1;
		Scanner k=new Scanner(System.in);
		int sum=0;
		while(sum<4000000)
		{   int f3=f1+f2;
			f1=f2;
			f2=f3;
			if(f3%2==0)
			{
				sum=sum+f3;
				
			}
		}
		System.out.println(sum);
	}
	public static void main(String []args)
	{
		series();	
	}
}
